### PR TITLE
Fix #104 - Change path.posix.relative to path.relative

### LINKED ISSUE #104: TypeError: Cannot call method 'relative' of undefined
After I did `npm install` and trying to run the app using `gulp watch` I'm seeing this error:

```
[13:47:14] TypeError: Cannot call method 'relative' of undefined
    at IndexFileStream._read (/Users/ali/projects/Mozilla-Learning/lib/gulp-index-file-stream.js:35:27)
    at IndexFileStream.Readable.read (_stream_readable.js:341:10)
    at IndexFileStream.Readable.on (_stream_readable.js:720:14)
    at IndexFileStream.Readable.pipe (_stream_readable.js:575:10)
    at Gulp.gulp.task.gulp.src.pipe._.extend.watch (/Users/ali/projects/Mozilla-Learning/gulpfile.js:53:6)
    at module.exports (/Users/ali/projects/Mozilla-Learning/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/ali/projects/Mozilla-Learning/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/ali/projects/Mozilla-Learning/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/ali/projects/Mozilla-Learning/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
[13:47:14] Finished 'less' after 1.39 s
```

### PR DESCRIPTION
**Pull request by alicoding**
Closes #104

### CODE REVIEW

**Comment by alicoding** [comment]
@toolness R?

**Comment by toolness** [comment]
this fix won't work on windows alas. is there an npm module that relativizes urls?  or we could special case windows...

**Comment by toolness** [comment]
Cool! Um, do you think you could assign the `require()` call to `posixPath` just so people don't mistakenly think it's node's own `path` module?

**Comment by alicoding** [comment]
@toolness done! :D

**Pull request merged**
